[workspace]
resolver = "2"
members = [
    "kernel",
    "crates/hal",
    "crates/mm",
    "crates/sync",
    "crates/drivers",
    "crates/vfs",
    "crates/sched",
    "crates/syscall",
    "crates/abi",
    "crates/libnox",
    "userland/nsh",
    "userland/ls",
    "userland/cat",
    "userland/echo",
    "userland/ps",
    "userland/mkdir",
    "userland/rm",
    "userland/cp",
    "userland/wc",
    "userland/grep",
    "xtask",
]

[workspace.dependencies]
bitflags              = { version = "2",    default-features = false }
spin                  = { version = "0.9",  default-features = false, features = ["spin_mutex", "rwlock", "once", "lazy"] }
x86_64                = { version = "0.15", default-features = false, features = ["instructions", "abi_x86_interrupt"] }
bootloader            = { version = "0.11" }
bootloader-api        = { version = "0.11", package = "bootloader_api" }
linked_list_allocator = { version = "0.10", default-features = false, features = ["use_spin"] }
libnox                = { path = "crates/libnox" }

[profile.release]
opt-level       = 3
lto             = "fat"
codegen-units   = 1
panic           = "abort"
overflow-checks = false
# No strip — userland ELFs need their sections intact (ELF loader reads them)
strip           = false

[profile.dev]
panic = "abort"
