[package]
name    = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
hal     = { path = "../crates/hal" }
mm      = { path = "../crates/mm" }
sync    = { path = "../crates/sync" }
drivers = { path = "../crates/drivers" }
abi     = { path = "../crates/abi" }
x86_64  = { workspace = true }
bootloader-api = { workspace = true }

[[bin]]
name              = "kernel"
path              = "src/main.rs"
